export { about } from './about';
export { achievement } from './achievements';
export { contact } from './contact';
export { course } from './courses';
export { footer } from './footer';
export { hero } from './hero';
export { navLinks } from './navLinks';
export { team } from './team';
export { testimonial } from './testimonial';
