import {
	anjali,
	anphil,
	anu,
	christeena,
	jeeva,
	karthika,
	lithin,
	wave,
} from '../../images';

export const team = {
	title: `Meet the team`,
	text: ``,
	background: `url(${wave})`,
	members: [
		{
			name: 'Dr Anphil Thomas',
			qualification: `Pharm D`,
			role: 'Founder and Director',
			highlight: true,
			message: `An accomplished educator and academic leader with a fascinating personality, Dr.Anphil Thomas is a believer for providing unique type of education. As the founder of the organization, he is committed to intensifying inclusion, equity of access to enhance a generating rich learning environment.`,
			photo: anphil,
		},
		{
			name: 'Dr. Karthika Jain',
			qualification: `Pharm D`,
			role: 'Inter Organizational Coordinator',
			highlight: false,
			message: `Completed her Pharm D from PSG College of Pharmacy Coimbatore in 2015. She is working as the Onsite Coordinator of our Academy.`,
			photo: karthika,
		},
		{
			name: 'Dr. Lithin Philip',
			qualification: `Pharm D`,
			role: 'Faculty',
			highlight: false,
			message: `With a Pharm.D degree from Rajiv Gandhi University, Bengaluru in 2016. He has successfully cleared KAPS in 2018.`,
			photo: lithin,
		},
		{
			name: 'Dr. Anu Thomas',
			qualification: `Pharm D`,
			role: 'Faculty',
			highlight: false,
			message: `With a Pharm.D degree from Rajiv Gandhi University, Bengaluru in 2017. She has successfully cleared KAPS in 2018.`,
			photo: anu,
		},
		{
			name: 'Dr. Christeena James',
			qualification: `Pharm D`,
			role: 'Faculty',
			highlight: false,
			message: `With a Pharm.D degree from Rajiv Gandhi University, Bengaluru in 2017. She has successfully cleared KAPS in 2019.`,
			photo: christeena,
		},
		// {
		// 	name: 'Dr. Aswathi George',
		// 	qualification: `Pharm D`,
		// 	role: 'Faculty',
		// 	message: `Pharm.D degree from Rajiv Gandhi University, Bengaluru in 2017. She has successfully cleared KAPS in 2019. She has over a year of experience as a Clinical Pharmacist in a reputed hospital in Kerala.`,
		// 	photo: ,
		// },
		{
			name: 'Ms. Jeeva Kletus',
			qualification: ``,
			role: 'Faculty',
			highlight: false,
			message: `Completed M. Pharm in Pharmacy Practice degree from Amrita University, Kochi in 2016. She has successfully cleared KAPS in 2019.`,
			photo: jeeva,
		},
		{
			name: 'Ms Anjali M Babu',
			qualification: ``,
			role: 'Faculty',
			highlight: false,
			message: `M. Pharm Pharmacology degree from Kannur Medical College, Kerala in 2017. She has successfully cleared KAPS in 2019.`,
			photo: anjali,
		},
	],
};
